version: 2
jobs:
  build:
    docker:
      - image: amazonlinux
    steps:
      - checkout
      - run:
          name: Get Pip
          command: |
            curl -O https://bootstrap.pypa.io/get-pip.py && python get-pip.py
      - run:
          name: Pip install AWS CLI
          command: |
            pip install awscli
      - run:
          name: Deploy Shared Resources via AWS CLI
          command: |
            #aws cloudformation deploy --stack-name ghc-workshop-shared-resources --template-file cfn/shared_resources.yml --capabilities CAPABILITY_NAMED_IAM --parameter-overrides WorkshopName="ghc-workshop" --region us-west-2
      - run:
          name: Deploy Application via AWS CLI
          command: |
            aws cloudformation deploy --stack-name ghc-workshop-application-1 --template-file cfn/application.yml --parameter-overrides SharedResourceStack="ghc-workshop-shared-resources" --region us-west-2
