version: 2
jobs:
  build:
    docker:
      - image: amazonlinux
    steps:
      - run:
          name: Get Pip
          command: |
            curl -O https://bootstrap.pypa.io/get-pip.py && python get-pip.py
      - run:
          name: Pip install AWS CLI
          command: |
            pip install awscli
      - run:
          name: Test AWS CLI
          command: |
            aws ssm get-parameter --name "circleci-key" --region us-west-2
